GET http://localhost:5000/api/user
Content-Type: application/json

###

GET http://localhost:5000/api/profile
Content-Type: application/json

###

POST http://localhost:5000/
Content-Type: application/json

###

